### ISSUE TITLE
[feature] drop-down menu button

### ISSUE THREAD

**Issue by atomGit** [nDimensional/prototype#1]
no doubt people are going to be requesting lots of c0ol things for this cool extension and in that vein i might suggest adding a little button in a corner that reveals a context menu

perhaps the first item that could be incorporated is 'Theme' and have a light and dark option that toggles the CSS instead of the keyboard shortcut (which i know i will forget as soon as i delete the default note)

thanks for creating this - maybe there are others for FF, but this is the first i've seen

**Comment by joeltg** [comment]
Good suggestion! I had played with a few different ways of implementing this but they all looked visually distracting (so I stuck with just the shortcut). I'll keep experimenting and will update if I find something I like.

**Comment by joeltg** [comment]
This happened! There's no GUI for it but there's a sidebar panel that you can toggle with cmd-period.
