### ISSUE TITLE
Command + Period doesn't close the settings

### ISSUE THREAD

**Issue by Jomanw** [nDimensional/prototype#4]
Using chrome

**Comment by joeltg** [comment]
Which version are you using? I tried to fix this in 0.4.2 :-)

**Comment by joeltg** [comment]
fdjakfljdskal
fas
sutffdsa

**Comment by rtran9** [comment]
how much do you care about the platform instructions?

mine reads 

> Ctrl-Period

but should be 

> Windows-Period

**Comment by joeltg** [comment]
Ah good catch - although I think I do want use the Ctrl key, not the Windows key (there's a bug in the implementation, not the label).

Does that make sense / which one would you expect? The Windows key feels like I powerful thing that you're not supposed to invoke

**Comment by rtran9** [comment]
`Ctrl` is what I expected and makes more sense. The windows key definitely feels out of the ordinary. I didn't notice this behavior until now, but if you're in a text cursor then using `Windows-period` removes the panel _and_ writes a period .... that doesn't sound right.

**Comment by joeltg** [comment]
Fixed in version 0.4.4 - update yourselves in chrome://extensions
