### ISSUE TITLE
Indented lists

### ISSUE THREAD

**Issue by joeltg** [nDimensional/prototype#6]
Should be able to indent lists; most people expect this.

Picking a text basis for this might be tricky - using tab characters is intuitive but might conflict with inline tables when they land. The other option is using spaces, which only look good/line up well in multiples of 2, but then that leaves ambiguity open on what to render and how to handle when there's an odd number.

My initial leaning is to use tabs, and just to not allow lists inside table cells (which is likely anyway).

**Comment by joeltg** [comment]
fixed in version 0.4.4 (now live in chrome web store)
thanks @kennethshawfriedman

**Comment by pkhart** [comment]
I would like to be able to indent all text, not just lists.

**Comment by joeltg** [comment]
no
